### ISSUE TITLE
Modify path for the current session only

### ISSUE THREAD

**Issue by andreiborisov** [jorgebucaran/nvm.fish#101]
👋

**What's the problem?**

- I have a bunch of fish scripts that run in the background and use system-wide installation of `node`. Global modification of `PATH` breaks them.
- I have different projects I work in parallel that use different node versions. Modification of `fish_user_paths` affects all terminal sessions, therefore, all projects.
- ~~I want to write a wrapper around `node` that will automatically call the appropriate `node` version based on the context (without the need to call `nvm` explicitly, mainly for the scripts) and would love to use this package as a dependency.~~

**Proposed solution**

- Make path modification behavior configurable through a variable. If the user chooses to, do not modify universal `fish_user_paths`, instead modify global `PATH` variable on the command usage that will affect only the current fish session.

Are you willing to review and accept a PR for this?

Related: https://github.com/jorgebucaran/fish-nvm/issues/93

**Comment by yegorius** [comment]
This has already been discussed in #39. Please see my last [comment](https://github.com/jorgebucaran/fish-nvm/issues/39#issuecomment-522186374) there. I hope @jorgebucaran will include proposed changes into official version, as this feature has been requested multiple times.

**Comment by jorgebucaran** [comment]
@yegorius @schrodincat Maybe you folks can help me test @schrodincat's proposal by writing a list of pros and cons for that approach. 🙏

**Comment by yegorius** [comment]
In my case I am almost always satisfied with my distro's default package of node (Arch Linux is rolling release distro so I get the latest official version of node in a matter of days), except for the special cases when some project requires an older version. In this case I temporarily switch with `nvm` in particular fish session while working on this project and I don't need the switch to be global or persistent.

**Comment by ujwal-setlur** [comment]
I need to different node versions in different shells...have older projects that work on node 10 only :-(

**Comment by jorgebucaran** [comment]
I want to rewrite nvm.fish using Fish 3.0, and I'm trying to figure out what to do about this issue.

We could check for a `.nvmrc` file whenever PWD changes, and switch versions for that specific session only. But how do we persist that version when your Node program spawns a child process?

@yegorius @andreiborisov @ujwal-setlur @jackwestmoretab

**Comment by jorgebucaran** [comment]
We could check for an `.nvmrc` file whenever PWD changes, and switch versions for that specific session only. But how do we persist that version when your Node program spawns a child process?

@yegorius @andreiborisov @ujwal-setlur @jackwestmoretab @thernstig

**Comment by andreiborisov** [comment]
> But how do we persist that version when your Node program spawns a child process?

Modify the global `PATH` instead of universal `fish_user_paths`. `PATH` is exported and should be inherited by child node processes.

**Comment by jorgebucaran** [comment]
Of course! Thanks, @andreiborisov!

**Comment by thernstig** [comment]
@jorgebucaran I definitely agree to modifying `PATH` for the current session only. I think that still having a possibility to modify "the global node version" is a good idea. Using/finding an `.nvmrc` in the directory tree would take precedence over the global one. This means you can easily walk in/out of project dirs but when outside them you still have some globally configured node version one can use e.g. for one-off `npx install`.

Even with that solution (allowing both "local" and "global" versions), I still have a slight problem with `fish_user_paths`. Reason being the way it works via specifying the full path to a path. This is bad for everyone [using dotfiles](https://medium.com/@webprolific/getting-started-with-dotfiles-43c3602fd789), syncing their config/dotfiles across machines. The solution to this might however lie upon fish itself, see https://github.com/fish-shell/fish-shell/issues/6641. But if it can be solved in this project as well that would be great. One way to solve it even for this project is to alter `PATH` as already suggested here for the project-local logic. In other words `PATH` would contain the path to the global configured node version, but when entering a directory it prepends the local, project-specific node version looking at `.nvmrc`.

But is the idea of automatically doing this by default when finding `.nvmrc` when PWD changes great? Some of us use tools like https://direnv.net/ which takes care of this for us for much more than just Node, so for us it could be problematic if you auto-switch.

**Comment by jorgebucaran** [comment]
Yes, and that's why we should only touch `$PATH`. I fully agree about avoiding `$fish_user_paths`.

**Comment by jorgebucaran** [comment]
Automatically switching versions when changing PWD should be easy to implement in userland (or perhaps even configurable—let's see), but never a default.

**Comment by jorgebucaran** [comment]
Hey! I just released [2.0](https://github.com/jorgebucaran/nvm.fish/releases/tag/2.0.0). Now we modify your PATH only for the current session, thus installing (or activating) a Node version only changes your local environment. 

See the [README](https://github.com/jorgebucaran/nvm.fish) for documentation. 👋 

@yegorius @ujwal-setlur @andreiborisov @thernstig
