### ISSUE TITLE
update npm

### ISSUE THREAD

**Issue by jimblue** [jorgebucaran/nvm.fish#104]
Hello,

I'm doing `nvm use lts` and it's working great. 😄 
But how can I update `node LTS` using NVM when a new version is released?

Cheers

**Comment by jorgebucaran** [comment]
@jimblue Hey!

Running `nvm use lts` should do the trick, if the version is already available in  https://nodejs.org/dist/npm-versions.txt.

Is that what you mean?

**Comment by jimblue** [comment]
ok thanks @jorgebucaran 😄
