### ISSUE TITLE
Universal variable 'fish_user_paths' is shadowed by the global variable of the same name.

### ISSUE THREAD

**Issue by iq-dot** [jorgebucaran/nvm.fish#105]
Hi, I seem to be getting this issue when I run `nvm` any help please? It downloaded the node version then I get this error.

**Comment by jorgebucaran** [comment]
@iq-dot False alarm?

**Comment by iq-dot** [comment]
Yes, turns out something else was setting that variable in Config which
caused this issue

**Comment by jorgebucaran** [comment]
@iq-dot Thank you for clarifying that! 👋

**Comment by arve0** [comment]
I experienced the same, a ruby installation caused it here. Found it by searching the fish-configs:

```sh
$ rg fish_user_paths ~/.config/fish
/Users/arve/.config/fish/config.fish
1:set -g fish_user_paths "/usr/local/opt/ruby/bin" $fish_user_paths
```

`-g` is global. Removed it and nvm works again.

**Comment by malimccalla** [comment]
I had the same issue when trying to run `nvm use 14.16.1`. I fixed it by removing the following two lines found in my `~/.config/fish`

```fish
set -g fish_user_paths "/usr/local/opt/python@3.8/bin" $fish_user_paths
set -g fish_user_paths "/usr/local/sbin" $fish_user_paths

**Comment by jorgebucaran** [comment]
Nvm doesn't use `fish_user_paths` anymore.
