### ISSUE TITLE
npm not present?

### ISSUE THREAD

**Issue by syeare** [jorgebucaran/nvm.fish#110]
I don't understand how to get npm. I thought npm installed alongside node if I do `nvm use 10.21.0`, but the command (npm) isn't recognized regardless of whatever version of node I get. If I try to install npm using apt, it installs an old version of node along with it instead of the version I need. Is there any way to fix this?

**Comment by jorgebucaran** [comment]
> @syeare I thought npm installed alongside node if I do nvm use 10.21.0, but the command (npm)

The `npm` command should be available after running `nvm use ...`. I wonder if there's a problem with your `$PATH` variable. What is your OS and fish version? Are you also using fisher? If so, what version?

**Comment by syeare** [comment]
The only thing in my $PATH is a path to the binaries for Android Studio. I only installed fisher and bobthefish. Ah, and I also keep fisher up to date. My OS is Ubuntu LTS 18.04

**Comment by jorgebucaran** [comment]
@syeare Can you confirm it installs node and the `node` command is available?

Please also run:

```console
la ~/.config/nvm/10.21.0/bin
```

**Comment by syeare** [comment]
Yes that's actually the strangest thing! `node` is recognized and it works and runs fine (runs some *.js files fine), but `npm` somehow is not installed. 
EDIT: Ok well now that I look at it again, it shows a link to where `npm` is supposedly installed but it doesn't launch some reason. I'll attempt to remove node/nvm/fisher/etc and then start from scratch.

Output of `la ~/.config/nvm/10.21.0/bin`:
![image](https://user-images.githubusercontent.com/11952166/87882166-d1917d00-c9c3-11ea-9424-abed1c235014.png)

**Comment by jorgebucaran** [comment]
@syeare Thanks. Could you show me the contents of your `$fish_user_paths`?

**Comment by syeare** [comment]
Oh I managed to fix it with a clean install of fisher, but thanks!
