### ISSUE TITLE
`nvm use` should switch to the version specified in .nvmrc

### ISSUE THREAD

**Issue by trajano** [jorgebucaran/nvm.fish#116]
The nvm.sh version sets the current node based on nvmrc when doing `nvm use` but this version fails with 
```
nvm: invalid version number or alias: ""
```

**Comment by jorgebucaran** [comment]
@trajano Try just `nvm`. This nvm's `nvm use` command expects a version like `nvm use xxx`. That's why.

**Comment by trajano** [comment]
Just tested back in zsh land

with nvm it shows the command options

<img width="627" alt="image" src="https://user-images.githubusercontent.com/110627/95710436-b0d96c00-0c2e-11eb-83ef-5719209524ed.png">

With `nvm use` it is doing what I was expecting.
<img width="736" alt="image" src="https://user-images.githubusercontent.com/110627/95710468-c484d280-0c2e-11eb-931f-a97e312c937d.png">

**Comment by jorgebucaran** [comment]
@trajano If you want `nvm` to install the node version defined in your closest .nvmrc file, you need an .nvmrc file.

From the docs:

> You can create a .nvmrc file in the root of your project (or any parent directory) and run nvm to use the version in it. nvm will try to find the nearest .nvmrc file, traversing the directory tree from the current working directory upwards.

Try this: add an .nvmrc file in your current directory and run `nvm` again:

```
echo 14.0.0 > .nvmrc
nvm
```

> Just tested back in zsh land

This project is not related to nvm-sh/nvm.
