### ISSUE TITLE
Fish 3.0

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/nvm.fish#122]
I'm working on a new, better nvm.fish, with a more consistent command-line interface (#81, #111), better XDG support (#108), and Fish `3.0` in mind. I also plan to fix long standing issues (#101, #112), so that switching versions only modifies the current shell. Here's the what I have in mind. All pretty straight-forward. Please let me know what we're missing and what else would you like to see?

Install the specified Node.js VERSION into `$XDG_DATA_HOME`.

```console
nvm install VERSION
```

Activate the specified Node.js version. Automatically install the version if it isn't already installed.

```console
nvm use VERSION
```

Use the version specified in the nearest `.nvmrc` or `.node-version` file, walking up the directory tree from the current working directory.

```console
nvm use
```

Print the Node.js version currently in use.

```console
nvm current
```

List all installed Node.js versions.

```console
nvm list
```

List Node.js versions you can install.

```console
nvm list-remote
```

Remove the specified Node.js version.

```console
nvm remove VERSION
```

**Comment by jorgebucaran** [comment]
If you wish to switch Node.js versions automatically when `$PWD` changes, creating a configuration snippet or adding this code to your `config.fish` should be simple enough.

```fish
function _nvm_on_pwd --on-variable PWD 
    test -e $PWD/.nvmrc || test -e $PWD/.node-version && nvm use
end
```

Maybe we can offer this out of the box without degrading shell performance. Need to think about it more.

**Comment by thernstig** [comment]
This sounds great! I assume `nvm use` will also install the specified version in `.nvmrc` or `.node-version` if not already installed? And what happens if neither of the files is found when walking up the directory tree?

**Comment by jorgebucaran** [comment]
Yes, to the first question. And do nothing, to the second one. What do you think?

**Comment by thernstig** [comment]
I'd probably expect it to talk up at most 10 levels and stop looking after that. It should then probably print a message saying that it did not found any of the files from the current directory and 10 levels up.

**Comment by jorgebucaran** [comment]
Too arbitrary? I don't really see the issue with infinite levels. How deep could you be anyway?

Do you know what nvm-sh does by the way?

**Comment by ljharb** [comment]
nvm looks up forever until it hits /, or finds an nvmrc file. When none is found, it uses the “default” alias, or if that doesn’t exist, it errors.

**Comment by jorgebucaran** [comment]
Thanks, @ljharb. We should do that too. That's also what we currently do.

Do we also want an `nvm alias` command like in nvm-sh? cc @jackwestmoretab @thernstig @andreiborisov

**Comment by jackwestmoretab** [comment]
@jorgebucaran you mean, to allow the user to set their own aliases?

**Comment by jorgebucaran** [comment]
Correct. I've always found that part, let's say "unintuitive" about nvm-sh, but that might be just me.

**Comment by jackwestmoretab** [comment]
I personally just use the built-in aliases (e.g. `system`), so have no investment in setting my own :) 

Worth seeing what others think, though!

**Comment by thernstig** [comment]
I personally do not care for aliases, so I cannot see the use case. `system` does make sense though. But each to his own I suppose. Maybe hold it off until after 2.0 has hit, if someone requests it?

**Comment by jackwestmoretab** [comment]
> Maybe hold it of until after 2.0 has hit, if someone requests it?

Sounds sensible to me. And the important issue here IMHO is fixing the `set -g/-U ...` behaviour.

**Comment by jorgebucaran** [comment]
Okay. We're just going to prepend to the PATH on `nvm use`. Now, do we also want to prepend to the `PATH` on shell start? And if so, which version do we want to prepend to it? Say I have two tabs open, in one I used `nvm use 14`, in the other, `nvm use 15`. Now, I open a new tab. What does `node -v` print?

**Comment by ljharb** [comment]
In nvm, using doesn't change or set the default - however when you install a node version when none existed, it will set the default if none exists.

**Comment by jorgebucaran** [comment]
So `node -v` will print `14.x.x` in the new tab for the scenario I described above. 

For nvm.fish `2.0`, I'd prefer changing the default version every time you do `nvm use VERSION`. That means using `2.0` would be very much like using `1.x` for people that just like to switch node globally, _but_ without breaking existing sessions (or sub-shells they may spawn) using a different node.

Hope that makes sense.

**Comment by andreiborisov** [comment]
No, please don’t mess with the global node version. If you have personal fish scripts or some other stuff that use `node` (I have) they will break. Changing the global version should be either via a separate subcommand or not present at all.

The whole point of NVM is to use different Node versions side by side.

I’m also don’t understand why would you even need to change the global version? There are `brew` and other package managers that do the job just fine. Check for `.nvmrc` on shell startup, if nothing found, do not append `PATH`. It will contain your global node version, that you installed via `brew`, then. Simple and predictable.

**Comment by andreiborisov** [comment]
Also, a subcommand akin to `npm install --save-dev` that would create `.nvmrc` for you would be quite awesome to have. I mean, you’ll want to add `.nvmrc` every time you set up a new project and it should be quite trivial to implement.

For example:

```
nvm use 10 --save
```

**Comment by jorgebucaran** [comment]
@andreiborisov Did you read this part?

> ...but without breaking existing sessions (or sub-shells they may spawn) using a different node.

Imagine nvm-sh changed the `default` alias whenever people run `nvm use VERSION`. That's what I am planning to do. Why isn't that good?

**Comment by andreiborisov** [comment]
Sub-shells and other sessions are only part of the problem.

Let’s say you have an automatically run fish script that calls `node`. It expects one version, that you globally installed. You’ve worked on some Node projects, default nvm `node` version has changed. `node` version for that script changed too. It breaks.

Another thing to consider: what if you want to keep your default Node installation always up-to-date to have all security updates as fast as they land? With the `brew`-installed version it’s easy because it’s a system package manager. But now you have a pinned `nvm`-installed version by default. How do you keep it up-to-date?

The point is, the global installation has different requirements and use-cases.

And finally, it’s easier and more predictable. You global installation = your default. Why it matters? Let’s say you’ve worked on some Node projects last week. Which is your default node version now? You can’t be sure, you need to run `nvm current`. There is no even need for this command in my proposal.

Which brings me to: it’s easier to implement and maintain. You don’t need to store which one is the default. You check dynamically on `nvm use` or startup, you append `PATH`. That’s it.

**Comment by andreiborisov** [comment]
Regarding the depth of checking for `.nvmrc`: I suggest going up to the nearest Git repo. Checking for `.git` folder should be enough.

**Comment by jorgebucaran** [comment]
@andreiborisov Have you used either nvm or nvm.fish?

**Comment by andreiborisov** [comment]
I’ve used `nvm.fish` (it [broke my system-wide scripts](https://github.com/jorgebucaran/nvm.fish/issues/101) back then), but not familiar with the original `nvm`.

**Comment by andreiborisov** [comment]
Did I get something wrong about your proposed implementation? I've assumed you want to store the current node version and switch to it on fish startup automatically by appending `PATH`.

**Comment by jorgebucaran** [comment]
Thanks for clarifying that. Let me just clarify that we won't touch your `/usr/local/bin/node` or replace binaries, we are just going to change the `$PATH`. 

Now, what about functioning the same as `nvm-sh`?

**Comment by jorgebucaran** [comment]
>  You global installation = your default. Why it matters? Let’s say you’ve worked on some Node projects last week. Which is your default node version now? 

What do we do if there's no system node installed? Doing the same as nvm-sh makes sense. [See here](https://github.com/jorgebucaran/nvm.fish/issues/122#issuecomment-727835503).

**Comment by andreiborisov** [comment]
> Let me just clarify that we won't touch your /usr/local/bin/node or replace binaries, we are just going to change the $PATH.

That's exactly the issue. Fish will run `nvm.fish` before executing my system-wide fish scripts and the version of `node` will effectively change for them too. I'm talking about scripts like this:

```fish
#!/usr/local/bin/fish

set log 'path/to/logs'
node app.js >> $log
```

This **will not** call `brew`-installed version.

**Comment by jorgebucaran** [comment]
@andreiborisov Yeah, which is why I asked what about we function like nvm-sh? It's easier to implement and there's no need to run anything on startup, except for https://github.com/jorgebucaran/nvm.fish/issues/122#issuecomment-728141066, but that's not so bad.

**Comment by andreiborisov** [comment]
> What do we do if there's no system node installed? Doing the same as nvm-sh makes sense.

I suggest doing nothing. 99% of people who use Node have it already installed. In my opinion, if your project needs a specific version you'll create `.nvmrc` or run `nmv use` explicitly (assuming you going to read `.nvmrc` on startup).

That being said you can check for that case specifically like nvm-sh, I see no harm in that, aside from maybe it's being confusing in some circumstances. Mainly how it should behave if the user installs `nvm` first and global node after that? Is it going to ditch the nvm default?

**Comment by jorgebucaran** [comment]
> Mainly how it should behave if the user installs nvm first and global node after that? Is it going to ditch the nvm default?

Think it would. My understanding is that nvm-sh prepends the `default` (alias) node to the PATH. 

> `default` and `system` are different things.

**Comment by andreiborisov** [comment]
> there's no need to run anything on startup

But how would you read `.nvmrc`? You'll need to check on a startup and a directory change.

**Comment by andreiborisov** [comment]
> Think it would. My understanding is that nvm-sh prepends the default (alias) node to the PATH.

Sounds like the best of the both worlds then.

**Comment by jorgebucaran** [comment]
> @andreiborisov You'll need to check on startup and directory change.

This is too slow and wastes resources unless you only use your machine to develop in node. Maybe this could be behind an option or see https://github.com/jorgebucaran/nvm.fish/issues/122#issuecomment-727248662.

**Comment by andreiborisov** [comment]
> This is too slow and wastes resources unless you only use your machine to develop in node. Maybe this could be behind an option or see #122 (comment).

Hmm, yeah, you're absolutely right, unless it's async which can be tricky to implement. An option or just this snippet in the README sounds good to me.

**Comment by jorgebucaran** [comment]
So, to clarify, (implementation details aside) you don't want the `default` alias set every time you run `nvm use VERSION`, but perhaps only the first time you do _and_ node is not already in your system.

If so, then when do we set the `default` alias?

**Comment by andreiborisov** [comment]
> So, to clarify, (implementation details aside) you don't want to the default alias set every time you run nvm use VERSION, but perhaps only the first time you do and node is not already in your system.

I want [this script](https://github.com/jorgebucaran/nvm.fish/issues/122#issuecomment-728144014) to always use system-installed `node` and never `nvm`-installed. Except if no system node installation is present. 

> If so, then when do we set the default alias?

Never? Unless previously mentioned conditions are met.

**Comment by jorgebucaran** [comment]
Do you reckon this is the most common use case nvm users use nvm for? It aligns with what nvm-sh does, which itself indicates it is.

> Never? Unless previously mentioned conditions are met.

Fine. Do we want aliases too?

**Comment by ljharb** [comment]
One solution is for your script to `nvm use system` explicitly, or `nvm exec system` (assuming this project supports those).

With nvm’s solution, you’d only have to unset the default after the first `nvm install` command you ran (or, you could set it explicitly to “system”).

**Comment by andreiborisov** [comment]
> One solution is for your script to nvm use system explicitly or nvm exec system (assuming this project supports those).

It can be done, but it's less portable, and ideally, those scripts shouldn't be aware of all this.

**Comment by ljharb** [comment]
The command used to run your script could use nvm exec system?

**Comment by andreiborisov** [comment]
> Fine. Do we want aliases too?

I personally don't need aliases.

**Comment by andreiborisov** [comment]
> The command used to run your script could use nvm exec system?

It's somewhat the same. You'd need to check if `nvm` is present first with every script.

**Comment by jorgebucaran** [comment]
Agree with @andreiborisov. I'd prefer writing scripts without having to think of nvm. But we could introduce an `exec` command as well if requested. 

Btw, nvm-sh doesn't set the version when changing paths either (which is good), so that's another +1 for not doing that.

 > I personally don't need aliases.

I thought so too. But without aliases we won't be able to set node on startup if there wasn't a node already installed. How do we solve that without introducing aliases?

**Comment by ljharb** [comment]
You don’t need custom aliases to support “4” or “15.2” or “node” aliases, fwiw.

**Comment by jorgebucaran** [comment]
No, I mean, without aliases, (long sentence ahead): setting the node version on startup after the first `nvm use VERSION` _when_ there wasn't a node in the system already might be weird or unexpected. I feel that nvm-sh handles this nicely because it already has aliases.

The explanation we can give is that: we created a `default` alias for `VERSION` since there was no node to start with.

**Comment by andreiborisov** [comment]
Can't it be an implementation detail?

We can print a simple message with an explanation that the "global" version of `node` is installed and controlled by `nvm` since there was not `node` present on the system.

**Comment by jorgebucaran** [comment]
Okay, I have a pretty good idea of what we want now about switching versions in new sessions, etc. Let me know what else would be nice to have before it's too late! Just kidding. 😄

**Comment by andreiborisov** [comment]
> Do you reckon this is the most common use case nvm users use nvm for? It aligns with what nvm-sh does, which itself indicates it is.

I understand. But correct me if I wrong, POSIX shells are a bit different in this regard. They have separate startup configs for interactive and non-interactive sessions. So nvm-sh presumably won’t mess up with your global shell scripts that are non-interactive. In Fish it’s all the same.

We can still investigate an async implementation for automatic reading of `.nvmrc` files. I would love to help with this after you’ll finish with the core rewrite. Should work fast and lift the burden of manually typing `nvm use`.

**Comment by jorgebucaran** [comment]
@andreiborisov Do you want different behavior depending on whether the session is interactive or non-interactive? And if so, how so?

> We can still investigate an async implementation for automatic reading of .nvmrc files.

Interesting. You can start thinking about that now.

**Comment by andreiborisov** [comment]
> @andreiborisov Do you want different behavior depending on whether the session is interactive or non-interactive? And if so, how so?

No. I was just trying to explain why copying nvm-sh behavior 1-to-1 won’t work for Fish and why I don’t want `nvm use` to set the default alias unless the system-wide `node` is missing.

> Interesting. You can start thinking about that now.

Ok👌

**Comment by jorgebucaran** [comment]
I had to bring this up again. I noticed that nvm-sh sets the `default` alias automatically when there isn't a default one yet, which I think is not the same @ljharb said in https://github.com/jorgebucaran/nvm.fish/issues/122#issuecomment-727835503.  Maybe it's me who did something wrong, but have a look:

```console
$ nvm current
system
$ node -v
v15.2.0
$ nvm install 14.9.0
Downloading and installing node v14.9.0...
Local cache found: ${NVM_DIR}/.cache/bin/node-v14.9.0-darwin-x64/node-v14.9.0-darwin-x64.tar.xz
Checksums match! Using existing downloaded archive ${NVM_DIR}/.cache/bin/node-v14.9.0-darwin-x64/node-v14.9.0-darwin-x64.tar.xz
Now using node v14.9.0 (npm v6.14.8)
Creating default alias: default -> 14.9.0 (-> v14.9.0)
```

If this is indeed what nvm-sh does (and not a user mistake from my part), are we sure we _don't_ want this feature in nvm.fish? cc @andreiborisov

**Comment by ljharb** [comment]
That's what I said - *using* does not set the default, but *installing* does. I should correct my earlier comment though; it does this every time any version is installed, not just the first time.

**Comment by jorgebucaran** [comment]
Thanks! I wouldn't have a problem with that. @andreiborisov you against this, right? Just checking.

**Comment by andreiborisov** [comment]
> Thanks! I wouldn't have a problem with that. @andreiborisov you against this, right? Just checking. 

Yes, I’m against it, since it will break system-wide scripts. 

The main reason why I think nvm-sh is designed that way is for users not to type `nvm use` every session. Since we’ll have auto-loading of `.nvmrc` it won’t be a problem (I’m currently benchmarking synchronous solution to see if we even need to do async variant, I have a pretty good idea on how to implement it though). If you’re wary about this design decision, let me done autoloading first. In my opinion with autoloading it’s going to be a superior design compared to `nvm-sh` and we won’t need to set the `default` alias.

**Comment by jorgebucaran** [comment]
@andreiborisov I'm not sure if autoloading immediately when changing directories will be a _default_ feature, but I do want to make this easy for users. I might not use it, but I'm willing to be convinced this is worth it.

I have an update as well. I want to remove the `nvm use` command. I think it's useless. Install/use, it's the same. Just use `nvm install VERSION`. Objections?

**Comment by andreiborisov** [comment]
> I want to remove the nvm use command. I think it's useless. Install/use, it's the same. Just use nvm install VERSION. Objections?

👍 `nvm install` also like `npm install`, totally makes sense.

I would’ve removed `nvm current` too, since, without aliases, it is basically `node -v`.

**Comment by ljharb** [comment]
There is a huge difference; just because you want to use a version doesn’t mean you have the bandwidth, cpu time, human clock time, or desire to install it.

**Comment by jorgebucaran** [comment]
Frankly, I don't understand this point. We just need to download the version once and prepend it to the PATH. It's virtually instantaneous.

**Comment by ljharb** [comment]
Many people pay for bandwidth; many people use a version manager in CI, or on internet appliances that have very low cpu power; some may be using it in a docker container that has versions preinstalled and permissions locked down so nothing new can be installed. Additionally, many systems require compilation, and a mere download isn’t sufficient.

**Comment by andreiborisov** [comment]
> 👍 `nvm install` also like `npm install`, totally makes sense.

After giving more thoughts I’ve realized that `nvm use` may be a better name for it or otherwise it’ll be awkward when you use it on subsequent invocations since you won’t install anything then.

**Comment by ljharb** [comment]
Specifically, it’s very important for any command that a user knows, with certainty, whether it will require network access, and whether it will be potentially destructive (ie, make persistent changes). `nvm install` is both, `nvm use` is neither.

At the very least, if you’re going to do this, please pick a command name that won’t be confusing - ie, something that’s neither use nor install.

**Comment by andreiborisov** [comment]
> There is a huge difference; just because you want to use a version doesn’t mean you have the bandwidth, cpu time, human clock time, or desire to install it.

I prefer it to be automatic. Seems like a rarely encountered edge case...

Maybe something like `nvm cleanup` that would delete old distributions will prove to be useful or perhaps a setting to limit storage space/number of distros? How much space one Node distro eats up anyway?

**Comment by ljharb** [comment]
The mere *download* could cost the user money - not everyone lives in a country where internet is effectively unlimited. Disk space isn’t really my concern (which is why i didn’t mention it); disk space is effectively infinite and free at this point.

**Comment by jorgebucaran** [comment]
>  ...it’ll be awkward when you use it on subsequent invocations since you won’t install anything then.

Maybe you are fluxing "install" and "download" into one, but that's not always the case. In Fisher, `fisher install X` updates `X` if it's already installed. I don't find this awkward, but I concede opinion may vary. It's certainly not worse than having an additional `nvm use` command.

> At the very least, if you’re going to do this, please pick a command name that won’t be confusing - ie, something that’s neither use nor install.

There's no need to pick a different name. The proposal is not about changing how `nvm install` works, is about removing `nvm use`. This `nvm install` will be effectively the same as nvm-sh `nvm install`, which installs (if not already installed) and uses/activates the specified version.

**Comment by jorgebucaran** [comment]
> The mere download could cost the user money - not everyone lives in a country where internet is effectively unlimited. Disk space isn’t really my concern (which is why i didn’t mention it); disk space is effectively infinite and free at this point.

Is this on-topic? Sorry, I don't think we're really arguing about that. Maybe it's a reply to https://github.com/jorgebucaran/nvm.fish/issues/122#issuecomment-729884810. Not sure. FWIW I'm definitely not arguing against that. 👍

> ...some may be using it in a docker container that has versions preinstalled...

If Node is already pre-installed/downloaded, `nvm install` behaves as `nvm use`.

> Additionally, many systems require compilation, and a mere download isn’t sufficient.

People on those systems don't use Fish. We've never supported compilation AFAIR. It's a decent compromise.

**Comment by jorgebucaran** [comment]
BTW I'm also planning to do this. From the new documentation:

---

The `nvm install` command activates the specified Node version only in the current environment. If you want to set the default version for new shells use:

```fish
set -U nvm_default_node 12.9.1
```

---

Thoughts? @andreiborisov @thernstig @jackwestmoretab

**Comment by andreiborisov** [comment]
> Thoughts?

Looks good🙏

**Comment by jackwestmoretab** [comment]
> Thoughts?

Looks good to me 👍 

Thanks for taking the time over this, @jorgebucaran!

**Comment by jorgebucaran** [comment]
PR: #123 🙏

**Comment by thernstig** [comment]
I had a few comments that I did not think of before, but I suppose those were better left as comments in the PR. So that's where they are 😃

**Comment by jorgebucaran** [comment]
Does anyone want to join me for a good old bikeshedding session? 

<img width="1440" alt="スクリーンショット 2020-11-26 20 00 20" src="https://user-images.githubusercontent.com/56996/100342921-04a6e580-3022-11eb-9649-b2df33fe3751.png">

**Comment by thernstig** [comment]
I have _no_ idea which one of those are the best - the more I stare at them the more I keep changing my opinion 😝 Would an "already installed" be too verbose? (My opinion: Yes it would be too verbose)

**Comment by andreiborisov** [comment]
I would say, the first is a clear winner.

Checkmark is an unambiguous indicator that the version is present/available/installed/downloaded. The arrow does imply downloading specifically, but it often used as an action icon, so it can be mistaken as a call to action rather than a status:
<img width="513" alt="CleanShot 2020-11-26 at 17 13 17@2x" src="https://user-images.githubusercontent.com/13354491/100361249-fb5e4e80-300a-11eb-85a9-5f501f05a3b7.png">
<img width="512" alt="CleanShot 2020-11-26 at 17 14 24@2x" src="https://user-images.githubusercontent.com/13354491/100361254-fdc0a880-300a-11eb-9f14-c1acd37f71b3.png">

**Comment by jackwestmoretab** [comment]
> I would say, the first is a clear winner.

I agree 100%.

**Comment by thernstig** [comment]
@jorgebucaran maybe https://github.com/jorgebucaran/nvm.fish/issues/103 could be unpinned now?
And does the other pinned "https://github.com/jorgebucaran/nvm.fish/issues/82" need a slight re-write?

**Comment by jorgebucaran** [comment]
Done! Bullet list rewritten for 2.0. Also added a note! Thanks for reminding me of that. 💯
