### ISSUE TITLE
npm / node does persist in new shell

### ISSUE THREAD

**Issue by fabienheureux** [jorgebucaran/nvm.fish#125]
Whenever I open a new shell, the `npm` `node` command are not available, and I need to re-run `nvm use` for example to enable again node / npm.
Here are the version used:    
```
❯ fish --version
fish, version 3.1.2

❯ fisher --version
fisher, version 4.1.0
 
❯ nvm --version
nvm, version 2.0.1
```

I am on Pop OS (~ Ubuntu), and it is a fresh install.   
I use almost the same setup on another laptop, without any issue.  
  
Any idea how to debug ?

PS: Thanks a lot for this package, it is the first time in a long time I have an issue with it. It is really useful and well documented.

**Comment by jorgebucaran** [comment]
The `nvm install` command activates the specified Node version only in the current environment. If you want to set a default version, e.g., v14.0.0, for new shells use:

```fish
set --universal nvm_default_version v14.0.0
```

**Comment by fabienheureux** [comment]
RTFM once again...
Thanks for you reply :+1:
