### ISSUE TITLE
nvm.fish on Darwin ARM 404s looking for node install

### ISSUE THREAD

**Issue by bryansh** [jorgebucaran/nvm.fish#126]
```
nvm install latest
Installing Node v15.4.0 latest
Fetching https://nodejs.org/dist/v15.4.0/node-v15.4.0-darwin-arm64.tar.gz
nvm: Invalid mirror or host unavailable: "https://nodejs.org/dist/v15.4.0/node-v15.4.0-darwin-arm64.tar.gz"
```

https://nodejs.org/dist/v15.4.0/node-v15.4.0-darwin-arm64.tar.gz - is not found; I don't think that there is a Darwin ARM release...and that compiling from source is known to work.

**Comment by jorgebucaran** [comment]
@bryansh Are you using an M1 mac?

**Comment by bryansh** [comment]
I am!

**Comment by jorgebucaran** [comment]
@bryansh Cool! I guess the best we can do for now is improve the error message? We don't support compiling Node. How difficult would it be to add this?

**Comment by jorgebucaran** [comment]
@bryansh Cool! I guess the best we can do for now is improve the error message? We don't support compiling from the source, yet. Is that what you expected to happen? I guess I could look into this

**Comment by bryansh** [comment]
Ahh, I see - I think the non fish NVM compiles from source if there isn't a binary available (I saw it do this before migrating to fish).  It would be cool if nvm.fish did similar or to your point, set user expectations.

**Comment by jorgebucaran** [comment]
Closing in favor of #127.
