### ISSUE TITLE
Manual installation setup error

### ISSUE THREAD

**Issue by shyim** [jorgebucaran/nvm.fish#135]
```
❯ nvm install v15.6.0
An error occurred while redirecting file '/home/shyim/.local/share/nvm/.index.temp'
open: No such file or directory
nvm: Invalid index or unavailable host: "https://nodejs.org/dist/index.tab"
```

Fish Version: fish, version 3.0.2
Curl Version:  curl 7.64.0
OS: WSL2 (Debian)

Just calling ` curl https://nodejs.org/dist/index.tab` does work in CLI

**Comment by shyim** [comment]
Was my fault 😅 

Installed manuelly and forget to create `mkdir -p /home/shyim/.local/share/nvm/`

**Comment by jorgebucaran** [comment]
@shyim I'm glad you got it working. But for the record, I really only support installation by Fisher.
