### ISSUE TITLE
complete: Too many arguments

### ISSUE THREAD

**Issue by domoritz** [jorgebucaran/nvm.fish#144]
Since recently, I am getting lots of errors when running `fisher update`

```
~/.config/fish/completions/nvm.fish (line 1):
complete nvm --exclusive --long version --description "Print version"
^
from sourcing file ~/.config/fish/completions/nvm.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'update'

(Type 'help complete' for related documentation)
complete: Too many arguments
```

**Comment by jamesa** [comment]
Maybe something to do with 3e90b3209a05ecddf5741b111df18941a3adb94f ? Not sure.

**Comment by jamesa** [comment]
@jorgebucaran Thank you for fixing this. Looks like https://github.com/jorgebucaran/nvm.fish/runs/1994973294 shows the same error as here in the "Install Tools" step, but it didn't fail CI. I'm not familiar with GitHub workflows but is it possible to make the test fail if similar error messages occur?

**Comment by jorgebucaran** [comment]
It's an interactive thing (completions), so it's probably  not possible or too hard to test.
