### ISSUE TITLE
NVM_DIR convention not followed

### ISSUE THREAD

**Issue by lordlycastle** [jorgebucaran/nvm.fish#146]
The "other" nvm-sh tool uses `$HOME/.nvm` as their install dir. They get that from `$NVM_DIR` var. This tool does not follow that convention.

This is many bad side effect, mainly other tools expect nvm to follow that convention e.g. IntelliJ. Now you have to change `NVM_DIR` on shell startup config file AND tell IntelliJ about this custom path because IntelliJ is not aware of dynamic change from `config.fish`.

Can we make this tool also use `$NVM_DIR` so it's a drop in replacement for the nvm-sh?

Sadly in Unix world the new generation tool must be backwards compatible. Which limits evolution of tool but it is neccessary evil because without plug-&-play integration it's a pain to use/setup.

**Comment by jorgebucaran** [comment]
How do you propose we do that without a breaking change?

**Comment by jorgebucaran** [comment]
Maybe favor `NVM_DIR` if set?

**Comment by jorgebucaran** [comment]
This tool is really not a drop-in replacement for _that_ nvm. But maybe we could favor `$NVM_DIR` if set, then default to `$XDG_DATA_HOME` as we currently do. 

If you open a PR with the changes you need I'll have a look. I'm not planning to work on this myself, so closing.
