### ISSUE TITLE
pyenv fish: pvm

### ISSUE THREAD

**Issue by thernstig** [jorgebucaran/nvm.fish#153]
Hi @jorgebucaran!

Just a question, have you ever considered creating a `pvm.fish` (or `pyenv.fish`) to create a similar tool for Python. I'd of course guess you are busy as is with all the great tools you've developed. Still curious, and also if you think it is even feasible (considering Python projects often use virtual environments which is a bit different than how Node.js works).

**Comment by jorgebucaran** [comment]
Would it work similarly to nvm.fish? What would you change, add, or remove?

**Comment by thernstig** [comment]
I love how nvm.fish works, so I'd want it to be as similar as possible in its usage. But I am sure it would have its unqiue challenges in implementing it.

**Comment by jorgebucaran** [comment]
Sounds interesting. Further information welcome! 👍

**Comment by thernstig** [comment]
One good thing to know is that this will require downloading the source code and compile it. So dependencies need to exist like: https://github.com/pyenv/pyenv/wiki#suggested-build-environment 

This is because Python does not keep pre-packaged binaries, see for example on the latest release https://www.python.org/downloads/release/python-394/

**Comment by jorgebucaran** [comment]
Do you have any cool name ideas? 😄

**Comment by thernstig** [comment]
pyenv.fish 😆 or pvm (python version manager) ? Names are the hardest part of software engineering...
