### ISSUE TITLE
Invalid set default node for new shell

### ISSUE THREAD

**Issue by anggapw** [jorgebucaran/nvm.fish#160]
Hi,

I have installed the node via nvm.fish and configured it so that it can be used as the default node

![Screenshot from 2021-05-21 11-19-42](https://user-images.githubusercontent.com/67362656/119077565-04d9d980-b9e4-11eb-8618-39515a93d0b7.png)

but when I open a new terminal, an error appears as shown below

![Screenshot from 2021-05-21 11-20-24](https://user-images.githubusercontent.com/67362656/119077637-2dfa6a00-b9e4-11eb-9121-b013a573fb6b.png)

do I have to reboot first? or I have to install nodejs separately on the system? i'm using Fedora 34

**Comment by jorgebucaran** [comment]
You need to install it before you can use it. So, `nvm install lts`, then `nvm use lts`.

**Comment by anggapw** [comment]
> You need to install it before you can use it. So, `nvm install lts`, then `nvm use lts`.

I've done it, but still can't

![Screenshot from 2021-05-21 13-13-54](https://user-images.githubusercontent.com/67362656/119085629-9e5cb780-b9f3-11eb-9564-275e37ebb9f4.png)

`
nvm: Node version not installed or invalid: "lts
`

**Comment by jorgebucaran** [comment]
Sorry, I can't reproduce this, and you are not giving me enough information to work with. 

Try debugging it here yourself:
https://github.com/jorgebucaran/nvm.fish/blob/e944905cdfea9c2261ea0c35043fb4848915c528/functions/nvm.fish#L112-L119
