### ISSUE TITLE
Migrating NVM from zsh to fish

### ISSUE THREAD

**Issue by Gibbo3771** [jorgebucaran/nvm.fish#163]
I am migrating from zsh to fish and I already have NVM installed and a whole bunch of node versions.

Is there any special setup I have to do to ensure nvm.fish uses the existing nvm version?

**Comment by jorgebucaran** [comment]
No, there isn't. I guess someone who knows nvm-sh/nvm well could write a Fish script to help with that. 

If you'd like to write one and need help with Fish, feel free to ask questions here! 👋
