### ISSUE TITLE
Document method to return to system node

### ISSUE THREAD

**Issue by hildjj** [jorgebucaran/nvm.fish#39]
If there is a mechanism to turn fnm off, it doesn't seem to be documented.

**Comment by jbucaran** [comment]
@hildjj 

You can select your previous version yourself, or remove the version you just switched to ```fnm rm x.x.x``` or use a .node-version file, so that fnm is only active within a specific directory.

Does that help?

**Comment by hildjj** [comment]
`fnm rm (node -v)` worked.  Suggest this gets doc'd.

**Comment by maparent** [comment]
I tried removing (on mac) and it still uses the old binary that was copied in ~/.config/fnm/bin/node
Also it means if I go back and forth between system and specific version it must re-download. Not that enthusiastic about that solution. 
As for selecting the previous version, it's the fnm copy of my system node, which may not be the system node. (For one thing, the latter gets updated semi-automatically.)
So I'd really appreciate a `fnm system` command.

**Comment by hildjj** [comment]
Candidly, I went back to zsh. However, I'm happy to talk through my use case. 

I develop with a system-installed nodejs (via homebrew on OSX).  I like that it stays up-to-date when I update the rest of my local stack.  Periodically (usually when I get a CI failure on an older version of Node), I want to drop down to a given version, debug, then go back to the most recent version.

**Comment by jwhitmarsh** [comment]
Apologies if this is the wrong place for this, but I think it is linked - I would add that if you leave a directory with an `.fnmrc` the node version should switch back to system (assuming there isn't an `.fnmrc` in the new dir)

**Comment by jorgebucaran** [comment]
@jwhitmarsh It should be possible using your own `node` wrapper function. 

See also:
- #75 
- [`rewrite` branch](https://github.com/jorgebucaran/fish-nvm/tree/rewrite)
- https://github.com/jorgebucaran/fish-nvm/issues/39#issuecomment-452567988

**Comment by yegorius** [comment]
I have created a fork where you can revert to system node and which doesn't set node version globally. Basically, it doesn't use `$fish_user_paths` universal variable and only changes `$PATH` which only affects current fish session. Also, `nvm unuse` will reset the `$PATH` to its initial state.
https://github.com/yegorius/fish-nvm
