### ISSUE TITLE
Issues after clean install

### ISSUE THREAD

**Issue by lardissone** [jorgebucaran/nvm.fish#41]
I've just switched from zsh to fish, and installed fnm with fisherman.

It seems to be installed correctly but I'm getting an error with the completions, after typing any character after the fnm command it returns an inline error:
<img width="781" alt="lardissone 2017-01-21 12-01-03" src="https://cloud.githubusercontent.com/assets/59826/22176483/9ab11ea6-dfd1-11e6-86f4-a482d02cba0c.png">

Also, when I try to access to a folder with a `.nvmrc` file it apparently changes the version (at least if the version is not in the system it start the download) but after that node is not responding:
<img width="951" alt="fnmtest 2017-01-21 12-08-41" src="https://cloud.githubusercontent.com/assets/59826/22176527/8399a1d8-dfd2-11e6-8b48-2e1dd79a52a2.png">

Any idea? Is there a way to debug the error?

**Comment by jorgebucaran** [comment]
Related https://github.com/fisherman/fnm/issues/35

**Comment by jorgebucaran** [comment]
@lardissone Hi and welcome to fish! I think we've had this issue before and I thought we had fixed it. See the link posted above.

**Comment by lardissone** [comment]
@jbucaran thank you. I'm not sure if it's related to #35 because `npm<Tab>` works fine. The problem is with `node` command in my case. I will continue testing tomorrow.

**Comment by jorgebucaran** [comment]
In that case, the solution is probably the same as #35, but for the node wrap function.

**Comment by jorgebucaran** [comment]
@lardissone I went ahead and used the same patch from #35 to fix the node wrapper function. Please let me know if this solves the issue.

**Comment by lardissone** [comment]
@jbucaran perfect, node command now works again. I'm not sure why, but version switching is not working for me. Do I need to install anything else, or change something in `config.fish`?

**Comment by jorgebucaran** [comment]
@lardissone Great!

> version switching is not working for me

🤔 The version switching mechanism is basically the same one we use in [verman](https://github.com/fisherman/verman) which seems to be working alright and it's the one I use to version node.

I'll have a look tomorrow again, but please consider creating a new issue for this, it could be a bug.

Related:  [Usage](https://github.com/fisherman/fnm#usage).
