### ISSUE TITLE
Version switching not working

### ISSUE THREAD

**Issue by lardissone** [jorgebucaran/nvm.fish#42]
I've just started from scratch again, removed fnm and reinstalled again, and still no luck with the version switching.

I'm using `.nvmrc` files, but also tried with `.fnmrc` and no luck.

How can I help to debug it? I'm new to fish and I would like to start contributing.

Here's the flow I tried and no luck:

![image](https://cloud.githubusercontent.com/assets/59826/22228865/7ba7f3f8-e199-11e6-9d79-4615d0188130.png)

**Comment by jorgebucaran** [comment]
@lardissone I'm looking into this right now! What fish version you using?

**Comment by lardissone** [comment]
@jorgebucaran I'm on this version:
`fisherman version 2.11.0 ~/.config/fish/functions/fisher.fish`

**Comment by jbucaran** [comment]
@lardissone fish is the shell, fisherman is the "plugin manager" that helps getting/updating/removing "plugins". I mean what fish version.

I suspect something changed in a recent fish version that does not allow to override system commands with shell functions. If that's the case, we are just a --flag away from fixing this issue.

**Comment by jbucaran** [comment]
@lardissone Ok! I figured it out, probably.

Just to make sure, do me a favor and type this in your terminal, then paste the result here so I can check.

```fish
type node
```

**Comment by lardissone** [comment]
@jorgebucaran sorry, I read wrong.
Fish version: `fish, version 2.4.0`

And `type node`:
`node is /Users/lardissone/.config/fnm/bin/node`

**Comment by jbucaran** [comment]
> node is /Users/lardissone/.config/fnm/bin/node

There you go! This is wrong and it's our fault. I'm fixing this and the patch should be up soon. Then you'll be able to `fisher update fnm`.

Thanks for reporting this.

**Comment by jorgebucaran** [comment]
@lardissone Give it another shot. I think we are clear now!

**Comment by lardissone** [comment]
@jorgebucaran amazing! It now works flawlessly! Thank you!

**Comment by Anenth** [comment]
I am also facing the same issue. 
![screenshot 2018-02-02 18 20 28](https://user-images.githubusercontent.com/1499218/35734053-c459f708-0845-11e8-8491-4912d8812b70.png)

my fnm version is `v1.8.3`
