### ISSUE TITLE
fnm doesn't work when navigating to the directory with .fnmrc, .nvmrc or .node-version

### ISSUE THREAD

**Issue by liubko** [jorgebucaran/nvm.fish#43]
Hi, I just installed `fnm` and trying to make it work, would appreciate if you can help me to fix the issue.

- fnm v1.8.0
- fish v2.4.0

![screen shot 2017-02-16 at 9 28 33 pm](https://cloud.githubusercontent.com/assets/4257937/23037413/e9259a04-f48e-11e6-9013-eff8dacc62e0.png)

**Comment by jorgebucaran** [comment]
Hi @liubko, can you share your fish version and OS?

**Comment by liubko** [comment]
- macOS Sierra v10.12.1
- fish v2.4.0

**Comment by josalmi** [comment]
This happened to me when I had [Fisherman NVM](https://github.com/fisherman/nvm) installed prior to installing fnm. Both plugins have defined nvm.fish and node.fish functions which might be causing conflicts.

**Comment by jbucaran** [comment]
@josalmi Thanks for sharing this.

**Comment by will-stone** [comment]
I'm having the same problem with Fish 2.6.0, fnm 1.8.2, macOS 10.12.6, and I don't believe I ever installed Fisherman NVM.

**Comment by JorgeBucaran** [comment]
@wesbaker Ping 😉

**Comment by will-stone** [comment]
The only other Fish item I have installed is https://github.com/rafaelrinaldi/pure. Not sure if that helps...?

**Comment by jorgebucaran** [comment]
@will-stone These days I am on [verman](https://github.com/fisherman/verman), but wesbasker may be able to help you out when he gets a chance to see this.

**Comment by will-stone** [comment]
Ah, thanks @JorgeBucaran I'll give verman a go. Is that considered the successor to fnm? (I'm a proper fish newbie, having only installed it this morning after getting frustrated with how slow zsh is)

**Comment by jorgebucaran** [comment]
@will-stone Not really, after `fnm`'s source grew "too big for my taste" I decided to make a new simpler tool and `verman` was born. Mostly to version node and go, ~~but there's ruby support too~~.

**Comment by will-stone** [comment]
So I wiped my fish installation completely. Started again, installed Fisherman, installed fnm, but same issue. Please also note, that where a folder contains a node-version file, not even the fnm command works.

**Comment by wesbaker** [comment]
@will-stone I think I have a solution. I’ll post it once I get to my desk.

**Comment by wesbaker** [comment]
@will-stone mind trying the fix in #53? You should just need to change the code in `~/.config/fisherman/fnm/functions/__fnm_run_bin_as.fish`

**Comment by will-stone** [comment]
that looks to have fixed it 👍
