### ISSUE TITLE
BSD support 

### ISSUE THREAD

**Issue by howdoicomputer** [jorgebucaran/nvm.fish#44]
Looks like you're checking for the OS here:

https://github.com/fisherman/fnm/blob/503b07d3b419908409373699c227c4baf32b4b7b/functions/__fnm_version_download.fish#L6-L23

Also, this code isn't putting out an error for me: 

https://github.com/fisherman/fnm/blob/503b07d3b419908409373699c227c4baf32b4b7b/functions/__fnm_use.fish

```
howdoicomputer@spacebison ~/w/findahome> fnm 6.9.5
howdoicomputer@spacebison ~/w/findahome> echo $status
0
howdoicomputer@spacebison ~/w/findahome> which node
howdoicomputer@spacebison ~/w/findahome> node -v
fish: Unknown command 'node'
```

I may look into drafting a pull request for you!

**Comment by jorgebucaran** [comment]
@howdoicomputer Cool! Looking forward to that.

**Comment by howdoicomputer** [comment]
Hah, I ended up going back to Linux. Oh wells.

**Comment by jbucaran** [comment]
😆

**Comment by jorgebucaran** [comment]
Bummer! Happy to accept PRs to add BSD support. 👋
