### ISSUE TITLE
.nvmrc should be searched by traversing the directory tree up

### ISSUE THREAD

**Issue by josalmi** [jorgebucaran/nvm.fish#45]
It would nice if .fnmrc file in parent directory would be applied to all child directories. This can be implemented by traversing the directory tree up while searching the .fnmrc file. 

Example:
mkdir -p parent/children
cd parent
echo "6.9.3" > .fnmrc
node -v # Should be 6.9.3
cd children
node -v # Should also be 6.9.3

[See NVM](https://github.com/creationix/nvm/blob/master/nvm.sh#L185)

**Comment by jbucaran** [comment]
@josalmi Sounds good to me! 👍

**Comment by jorgebucaran** [comment]
Related #78.

**Comment by jorgebucaran** [comment]
@josalmi I finally did it. e2f6fb9 adds this behavior. It works by finding the nearest `.nvmrc` file, traversing the directory tree from the current working directory upwards.

**Comment by josalmi** [comment]
Superb! Thanks for all the good work you are doing for the community.
