### ISSUE TITLE
Use package.json engines configuration for version

### ISSUE THREAD

**Issue by emilyhorsman** [jorgebucaran/nvm.fish#46]
`fnm` could try to select a version with the [`engines`](https://docs.npmjs.com/files/package.json#engines) rule in `package.json` if it exists. `nvm` has some precedent for this in [this discussion](https://github.com/creationix/nvm/issues/651) and [this PR](https://github.com/creationix/nvm/pull/1535).

I've never written any `fish` but I could give a PR for this a shot if maintainers are open to it being merged.

**Comment by jorgebucaran** [comment]
@emilyhorsman Yes, I'd be happy to merge a PR for this, but we'll need to be clever about how we implement it since this kind of file parsing is going to be slow-ish. 🤔

**Comment by emilyhorsman** [comment]
@jorgebucaran That makes sense!

`jq` comes to mind (although it would require users that want this feature to install a binary). It's very fast.

```bash
> jq --monochrome-output --raw-output '.engines.node' package.json
6.11.0
```

**Comment by jbucaran** [comment]
Sure, jq is fast! But imposing a dep on users isn't much so. I think using some simple heuristics, Awk can save the day again. Are you familiar with Awk? If you are not I'd be glad to help out.

**Comment by LukeChannings** [comment]
I like this idea!

You could use Node itself to extract the supported engines like:

`set engine (node -p 'require("./package.json").engines.node' ^ /dev/null)`

However, the engine value will not necessarily be as clean as @emilyhorsman's example, with semver ranges being somewhat common.

Something like [npm/node-semver](https://github.com/npm/node-semver) and `fnm list` would be needed to find the latest compatible version.

**Comment by jbucaran** [comment]
@emilyhorsman @LukeChannings Can you post one or more example of package.json using engines in the wild and the version you would expect fnm to select for you? If I have a clear "spec", I could give it a shot using only awk and regex.

**Comment by LukeChannings** [comment]
It won't be possible to parse it with `awk`, because the engine string does not contain an actual version necessarily, it specifies versions of Node that it's compatible using semver notation, documentation for which can be found here - https://docs.npmjs.com/misc/semver#ranges.

The steps to find an appropriate version to execute a project with would be something like:

1. Extract the engine specified in package.json's engines.node as $engine
2. if $engine starts with one of: ^, ~, or [0-9], strip the ^ or ~ and use the version remaining
3. if $engine is a semver range:
    1. Extract a list of available Node versions into a list as $available-engines
    2. Sorted by highest number, test each available version satisfies the semver version using [node-semver](https://github.com/npm/node-semver) or similar's maxSatisfying($available-engines, $engine)

For trivial cases defined in 1, you could use `awk` or `sed`, but there are many more cases than that, and `node-semver` handles them correctly.

I fear that without some dependencies this will not be possible to implement.

**Comment by jorgebucaran** [comment]
Can you share examples just to get an idea of what we are doing here?

**Comment by LukeChannings** [comment]
Sure, here are a few packages that use engines and devEngines:

- [Lodash](https://github.com/lodash/lodash/blob/master/package.json#L7)
- [React](https://github.com/facebook/react/blob/master/package.json#L103)
- [Webpack](https://github.com/webpack/webpack/blob/master/package.json#L72)
- [ A CLI I wrote](https://github.com/LukeChannings/translate-json-cli/blob/master/package.json#L14)

**Comment by jorgebucaran** [comment]
@LukeChannings Sweet, thanks! So, if the root directory has the following `package.json`:

```js
"engines": {
  "node": ">=4.3.0 <5.0.0 || >=5.10"
}
```

How would you expect `fnm` to behave in the following scenarios:

1) User moves into the directory.
2) User runs `fnm` inside the directory.

Please add any missing scenarios or correct me if I typed any nonsense above.

**Comment by franciscolourenco** [comment]
1. node changes to latest stable version
2. normal interactive UI appears

**Comment by jorgebucaran** [comment]
SGTM

**Comment by mrchief** [comment]
Relying on node itself is more robust than relying on tools like awk. Not safe to assume every linux distro comes with awk pre-installed.

**Comment by jorgebucaran** [comment]
~~awk is included by default on all UNICES~~ (not by default in some apparently). Problems may arise from _different_ versions though. Having said that, if you are using fnm, it's safe to assume the user has Node.js installed.

**Comment by franciscolourenco** [comment]
@jorgebucaran https://www.archlinux.org/ doesn't come with awk or grep, only sed.

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"

$ awk
bash: awk: command not found

$ grep
bash: grep: command not found

$ sed --version
sed (GNU sed) 4.7
```

**Comment by jorgebucaran** [comment]
https://wiki.archlinux.org/index.php/Core_utilities#Essentials

**Comment by jorgebucaran** [comment]
Also going to close this since it's been more or less two years since this issue was opened and no work was done. I'm still open to a PR, of course! 👋

**Comment by franciscolourenco** [comment]
> https://wiki.archlinux.org/index.php/Core_utilities#Essentials

Thats nice, but they still don't come installed by default.
