### ISSUE TITLE
First time running fnm: I couldn't find '6.11.3' in the version index.

### ISSUE THREAD

**Issue by chrismwendt** [jorgebucaran/nvm.fish#51]
```
$ fisher fnm
$ fnm 6.11.3
fnm: I couldn't find '6.11.3' in the version index.
```

It seems to work after you run `fnm ls`. I'm guessing it has to first download the version index before being able to query it.

`fnm <version>` should probably automatically download the version index if it doesn't exist.

**Comment by JorgeBucaran** [comment]
> fnm <version> should probably automatically download the version index if it doesn't exist.

This sounds reasonable! 👍

**Comment by jorgebucaran** [comment]
@chrismwendt Took me a long time, but this is finally fixed. 👋 

See the [release notes](https://github.com/jorgebucaran/fish-nvm/releases/tag/1.0.0) to see what else changed or not.
