### ISSUE TITLE
Yarn support?

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/nvm.fish#52]
I installed the latest NPM package with `yarn` as:

    yarn global add npm@5.4.2

But still show another version

❯ npm --version
5.3.0

❯ whereis npm
npm: /usr/bin/npm /data/settings/.config/fnm/bin/npm /home/ed8/.yarn/bin/npm

❯ /usr/bin/npm --version
3.10.10
❯ /data/settings/.config/fnm/bin/npm --version
5.3.0

/data/projects/employee-app-front front-login-form-errors 
❯ /home/ed8/.yarn/bin/npm --version
5.4.2

How do I use the one from yarn?

**Comment by jorgebucaran** [comment]
Yeah, it doesn't support yarn.

**Comment by jorgebucaran** [comment]
~~I will look into this for the new version of this package. I don't know why we couldn't easily support this.~~

Nevermind. I thought you used npm to install yarn, but it was the other way around. I'm happy to accept a PR to add yarn support. I may still look into this in the future, but not now.

Closing! 👋

**Comment by treykasada** [comment]
I just came here looking for Yarn support (i.e. a `yarn` instance correlated to a given `node` version and stored in `~/.config/nvm/<version>/bin/`).

Any chance of this being revisited? 🙂

Am I correct in assuming the difficulty is in determining the ideal Yarn version for a given Node version? If so, would it be possible for now to simply pull down the latest Yarn version no matter the Node version, and iterate on that later?

**Comment by jorgebucaran** [comment]
Hi @treykasada! If you're willing to work on a PR that someone can review, I'm happy to revisit this. 👋

**Comment by ghost** [comment]
> Nevermind. I thought you used npm to install yarn, but it was the other way around. I'm happy to accept a PR to add yarn support. I may still look into this in the future, but not now.

I'm looking into using fish-nvm, but need to have yarn compatibility as well. I was wondering, if I install yarn via npm, that should do the trick right? I assume that if I switch node versions, npm will be up- or downgraded as well along with any associated global packages (and thus yarn)? (I'm not looking to install any global packages with yarn btw.)

**Comment by jorgebucaran** [comment]
> @ismay I'm looking into using fish-nvm, but need to have yarn compatibility as well. I was wondering, if I install yarn via npm, that should do the trick right?

Makes sense, why don't you try it out and report back your findings? We'd all appreciate that. 👋

**Comment by ghost** [comment]
Will do 😊👍

**Comment by ghost** [comment]
All right, so I've tested it locally and it works fine for me (yarn had been installed previously for each node version with `nvm use <version> && npm i -g yarn`):

<img width="298" alt="Screenshot 2020-05-08 at 13 30 24" src="https://user-images.githubusercontent.com/7355199/81401694-25642800-9130-11ea-9701-febb0a56feef.png">

I didn't try globally installing packages using yarn (and I don't intend to), so this seems perfectly fine. By the way @jorgebucaran, nice job on this lib, works like a charm 👍!

**Comment by ghost** [comment]
One thing where there might still be conflicts by the way, is the yarn cache (where it caches installed modules for faster subsequent installations): https://classic.yarnpkg.com/en/docs/cli/cache. But I'm not sure, I haven't tested that yet.

Edit: It uses a global dir. So on my system for example, that's:

```
> yarn cache dir
/Users/ismay/Library/Caches/Yarn/v6
```

So that'll be outside of the switching that nvm does.

**Comment by jorgebucaran** [comment]
That's an amazing @ismay, now I can finally say:

| Team    | Goals | 
|----------|---|
| fish-nvm | 1 | 
| World    | 0 |  

> But I'm not sure, I haven't tested that yet.

Darn, I'll have to wait until after the second period then. 👍

**Comment by ghost** [comment]
Haha, yeah I think we can still keep the score as-is:

<img width="194" alt="Screenshot 2020-05-08 at 14 06 44" src="https://user-images.githubusercontent.com/7355199/81404175-319eb400-9135-11ea-9595-c61e3c85195f.png">

It's just a tiny gotcha (plus it might not even be a problem), in an otherwise flawless victory 👍

**Comment by jorgebucaran** [comment]
'Twas a close match that one. Feel free to reopen if you get stuck on something.
