### ISSUE TITLE
npm ERR! Cannot find module 'internal/util/types'

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/nvm.fish#59]
**related:** npm/npm#19032, npm/npm#19166

Every time I switch to `4.2.6` and back to `8.x.x` I broke my NPM:

```
$ fnm use 4.2.6 
$ fnm use 8.9.3
$ npm install
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/util/types'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ed8/.npm/_logs/2017-12-12T15_02_45_814Z-debug.log
```

**Comment by edouard-lopez** [comment]
I managed to fixed it as follow, but the behavior is unexpected:

```
rm ~/.config/fnm/ -rf
fisher rm fnm
fisher install fnm
fnm use 8.9.1 
npm install
```

**Comment by jorgebucaran** [comment]
No idea what happened there. If you reproduce this, please reopen. The new version of this package is simpler, so it may be a bug in the old code base.

**Comment by jorgebucaran** [comment]
@edouard-lopez No idea what happened there. If you reproduce this, please reopen. It may be a bug in the old code base not present in the new version so closing for now.
