### ISSUE TITLE
Support Node.js LTS aliases

### ISSUE THREAD

**Issue by ngryman** [jorgebucaran/nvm.fish#60]
Hi guys, `nvm` has several aliases for `lts` versions that are not supported in `fnm`. For example: `lts/carbon` and presumably `lts/*` don't work and output the following error when a `.nvmrc` file is present:

```sh
fnm: It seems 'lts/carbon' is not a valid version number.
Hint: Examples of valid node versions:
       v5.10.1
        latest
          0.12
           lts
```

I think that if you want to support `.nvmrc` those aliases should also work with `fnm`.

**Comment by jorgebucaran** [comment]
I am okay with this if you want to create a PR! 👍

**Comment by ngryman** [comment]
Oh, @JorgeBucaran! 🎉 What a small world 😄

So from `nvm` docs, it seems that those versions are stored in `$NVM_DIR/alias/lts`. It would involve getting this file content and process it. I'm not sure that this feature request is worth the added complexity 🤔

**Comment by ngryman** [comment]
Back to this one, would you be open to support `lts/*` to increase `nvm` compatibility? If so I can open a PR.

**Comment by jorgebucaran** [comment]
@ngryman No problem. If you are using fnm and it makes sense to add this, go ahead and send me a PR.

**Comment by jorgebucaran** [comment]
#71 was merged so we can close. The new version of this package will additionally support following aliases:

- `lts` == `lts/*` == `lts/latest` == `latest/lts`
- `lts/carbon` == `carbon` == `carbon/lts` == `latest/carbon`
- Same as above for every existing codename

**Comment by jorgebucaran** [comment]
Done! 🎉 

Use any of following to install the latest LTS release:
```
nvm use lts
```
```
nvm use lts/*
```
```
nvm use lts/latest
```
```
nvm use latest/lts
```
