### ISSUE TITLE
Can't use with VSCode

### ISSUE THREAD

**Issue by bioball** [jorgebucaran/nvm.fish#61]
I'm just now trying out fnm. It seems to work great, except I'm not able to use this in conjunction with VSCode. It seems like the issue revolves around the fact that fnm overwrites the node executable with a fish function.

Here's the error that I get:

<img width="1794" alt="screen shot 2018-02-05 at 11 39 54 am" src="https://user-images.githubusercontent.com/4590460/35824949-505ee266-0a69-11e8-8346-0ddca528cb81.png">

**Comment by franciscolourenco** [comment]
fnm adds `/Users/user/.config/fnm/bin` to the path. Does your VSCode have a hardcoded PATH. Or maybe it is not using fish to get the `PATH`?

**Comment by jorgebucaran** [comment]
The new version of this package will overwrite the binary and change the PATH after switching versions, so we should be fine here.
