### ISSUE TITLE
[Feature Request] Automatically add node_modules binaries to PATH

### ISSUE THREAD

**Issue by devxpy** [jorgebucaran/nvm.fish#66]
Something like this already exists for [oh my fish](https://github.com/oh-my-fish/plugin-node-binpath). 

If you could integrate this functionality in fnm, that would be super nice.

**Comment by jorgebucaran** [comment]
Yes! The new version of this package will correctly modify the PATH after you switch to a node version.

**Comment by maqnius** [comment]
I'm sorry to be digging the ticket out of the grave but is this feature still existing or has it been moved elsewhere?

I'm using 2.2.18 (installed using Fisher) and it doesn't seem to add `node_modules/.bin` to the path.
