### ISSUE TITLE
Filter available versions shown with ls

### ISSUE THREAD

**Issue by jimt** [jorgebucaran/nvm.fish#76]
I often use nvm's ability to filter the output of `nvm ls-remote` to versions that start with the supplied optional argument.  For example `nvm ls-remote 10.2` shows 10.2.0 and 10.2.1.

Would it be useful to add similar functionality to fnm?

**Comment by jorgebucaran** [comment]
@jimt Yes, this will be in the new version. See #75.

**Comment by jorgebucaran** [comment]
This is done. 

Use:

```
$ nvm ls 10.2
 0.10.2    
0.10.20    
0.10.21    
0.10.22    
0.10.23    
0.10.24    
0.10.25    
0.10.26    
0.10.27    
0.10.28    
0.10.29    
 6.10.2    (lts/boron)
 10.2.0    (lts/dubnium)
 10.2.1    (lts/dubnium)
```
```
$ nvm ls \^10.2
10.2.0    (lts/dubnium)
10.2.1    (lts/dubnium)
```

**Comment by jgierer12** [comment]
Is it possible somehow to filter by name (e.g. `nvm ls boron` `nvm ls latest` `nvm ls lts`)?

**Comment by jorgebucaran** [comment]
@jgierer12 Nope. The query is limited to the version number.
