### ISSUE TITLE
What software did you use to capture the demo?

### ISSUE THREAD

**Issue by maticzav** [jorgebucaran/nvm.fish#83]
Hey 👋,

Sorry for polluting your issues section. I really like the demo video! Did you use any specific software to capture it?

Thanks a lot 🎉

**Comment by jorgebucaran** [comment]
Hi @maticzav, it's funny you ask. I recently switched to a new computer and lost the script I used to make it. I made it with the help of the following software:

- https://asciinema.org/
- https://linux.die.net/man/1/pv
- https://github.com/marionebl/svg-term-cli

Hope that helps! 👋
