### ISSUE TITLE
lts version issue

### ISSUE THREAD

**Issue by tomyun** [jorgebucaran/nvm.fish#87]
As of today (Jul 19, 2019), `nvm use lts` picks up 12.6.0 which is indeed a *Current* release, but not an Active LTS yet. I believe it should pick up 10.16.0 as what `nvm use dubnium` currently does, until v12 becomes LTS in [October](https://nodejs.org/en/about/releases/).

**Comment by jorgebucaran** [comment]
We just need to tweak how the index is generated in `_nvm_get_index`. PR welcome! @tomyun 👋
