### ISSUE TITLE
nvm compat issues

### ISSUE THREAD

**Issue by ntwb** [jorgebucaran/nvm.fish#89]
I just installed this package to hopefully have an improved _nvm_ experience with Fish shell...

Here's what I discovered:

Native nvm compat issues:
1. `nvm current` doesn't exist, in native nvm the `current` flag will list the current active Node.js version in use.
1. `nvm ls-remote` doesn't exist, in native nvm the `ls-remote` flag will list the available Node.js versions that can be installed
1. `nvm install x.y.z` doesn't exist, in native nvm the `install` flag will install the x.y.z specified or aliased version of Node.js.

fish-nvm issues:

1. `nvm ls` lists the remote Node.js versions that can be installed, though it incorrectly lists the Node.js v12.x releases as "LTS", The Node.js v10.x releases are the current "LTS" releases, Node.js v12.x doesn't enter "LTS" [until later this year](https://nodejs.org/en/about/releases/)
1. Running `nvm use lts` installs the latest v12.x release, I expected it to install the latest v10.x release

npm issues:
1. Installing `npm` is not straight forward, a fish _helper_ function for npm would be useful, I had to dig around looking for the included version of npm in the Node.js release installed, I expected it to use `~/.nvm` though fish-nvm actually installs Node.js into `~/.config/nvm/x.y.z`
1. Having the path as `~/.config/nvm/x.y.z` is troublesome for keeping _global_ packages installed between npm versions.

Anyhow, thanks for the fish-nvm package, after discovering the above issues I now understand how this fish-nvm package is expected to work so I'll play around some more and try to use the fish-nvm installed comments rather than the native nvm commands I'm used to, I think for the most part I should be able to work around most issues.

With the above workarounds, it would still be great to get some of these other aliases added to fish-nvm, primarily so that if instructed to run certain nvm commands from another repo those nvm commands would also be available in fish-nvm.

**Comment by jorgebucaran** [comment]
Hi @ntwb! 👋  

Compatibility with nvm-sh/nvm is not a goal, but I'm open to adjustments as long as they make sense for this nvm.

- This nvm doesn't have nvm current, but it could. If you want to add it, please send me a PR.
- To list the available Node.js versions use `nvm ls` with this nvm.
- This nvm doesn't have an install command; `nvm use` will both install and use the specified Node.js version.
- LTS issue: Yes, this has been brought up in https://github.com/jorgebucaran/fish-nvm/issues/87, and there's a fix here: https://github.com/jorgebucaran/fish-nvm/pull/88. If you can test it works as expected, it'd be easier for me to merge it.
- npm issue: This is a bug in this nvm, then, as I'd like it to install the npm bundled with the Node.js version I specify. Please create a new issue for this.
- I'm open to making modifications to where we install packages if it's not too hard. Please create a new issue to track this. 🙏

**Comment by ntwb** [comment]
Thanks, I'll take a look around in the coming days as I get used to using this nvm

To make it easier I'll close this issue and recreate specific issues as required


Thanks for the quick feedback 👍🏼
