### ISSUE TITLE
`nvm use lts` installs latest not lts version

### ISSUE THREAD

**Issue by kirach** [jorgebucaran/nvm.fish#90]
`nvm use lts` installs version 12.11.1 (as of oct, 7) while the latest lts version is 10.16.3 according to https://nodejs.org/en/download/

**Comment by jorgebucaran** [comment]
@kirach Thanks. How does one determine the LTS version in this case?

**Comment by ljharb** [comment]
same way nvm does - it’s in the index.tab file in nodejs.org/dist

**Comment by jorgebucaran** [comment]
@kirach Can you check if https://github.com/jorgebucaran/fish-nvm/pulls solves it for you? Thanks.

**Comment by jorgebucaran** [comment]
I tried it and it's working now. 🎉
