### ISSUE TITLE
Setting $NODE_VERSIONS and $NODE_VERSION_PREFIX

### ISSUE THREAD

**Issue by thernstig** [jorgebucaran/nvm.fish#92]
Projects suchs as [direnv can use node](https://github.com/direnv/direnv/wiki/Node), but it depends on that this is set:

```fish
set -gx NODE_VERSIONS ~/.config/nvm
set -gx NODE_VERSION_PREFIX ''
```

Is there any chance these could be set automatically in conf.d/nvm.fish or is it a bad idea?

**Comment by jorgebucaran** [comment]
I have no idea. I have never used `direnv`. Are those variables `direnv` specific?

**Comment by thernstig** [comment]
I see, I kind of thought you were aware due to https://github.com/direnv/direnv/wiki/Node#using-nvm-with-automatic-discovery but I suppose any user could have added that piece of text. Unfortunately they are `direnv` specific so I suppose that might make this out of scope for this project.

**Comment by thernstig** [comment]
Although I strongly recommend direnv if you work on multiple projects, which you surely do :)

**Comment by jorgebucaran** [comment]
@thernstig I had heard about it, but never used it. I'll definitely check it out again, thanks.

**Comment by brandonpittman** [comment]
Found myself having issues integrating nvm.fish with direnv as well.

Direnv has a handy `use node` function, but it requires a `$NODE_VERSIONS` env variable that points to a directory with `node` binaries. nvm.fish doesn't have such a directory, but I suppose it's possible to create a directory with linked binaries for this purpose.

**Comment by jorgebucaran** [comment]
What would a directory with node binaries be exactly? Currently, we download each version to its own directory inside `~/.local/share/nvm`, so for Node v17.0.1 you can find the binaries in: `~/.local/share/nvm/v17.0.1/bin`.

**Comment by brandonpittman** [comment]
direnv wants a single directory like this:

```
versions
	- node-14.7.2
	- node-17.0.1
```

…I think. I only started using it recently.

Then you set `$NODE_VERSIONS` to that path and direnv lets you call `use node`, looks up the version in `.nvmrc`, and sets it for you.

[direnv-node](https://direnv.net/man/direnv-stdlib.1.html#codeuse-node-ltversiongtcode)

I was thinking of writing a script that would create a dummy directory that had links to the node binaries nested in each of nvm.fish's version folders. 🤔

**Comment by jorgebucaran** [comment]
The way @thernstig set those variables [here](https://github.com/jorgebucaran/nvm.fish/issues/92#issue-512692884) should do it, no? Maybe `$NODE_VERSION_PREFIX` should be set to `v`, though.

**Comment by brandonpittman** [comment]
![CleanShot 2021-10-22 at 16 29 15@2x](https://user-images.githubusercontent.com/967145/138412147-58a912b8-f16e-4f41-adb3-fe2f1ee48b6f.png)

You'd think so, but apparently they can't find it in the nested `/bin` directory.

---

Tried the dummy dir with `ln`ed binaries…didn't work. 😆

**Comment by jorgebucaran** [comment]
Did you install v14.17.2 already? If you do, then it will be at `~/.local/share/nvm/v14.17.2`, and the binaries inside `bin`.

**Comment by brandonpittman** [comment]
Yeah, it's already installed.
![CleanShot 2021-10-22 at 16 37 33@2x](https://user-images.githubusercontent.com/967145/138413272-934e8db0-3125-4c54-b877-c9e62dc54b43.png)

**Comment by jorgebucaran** [comment]
We need someone that knows direnv well to explain what direnv expects inside `~/.local/share/nvm/v14.17.2`. 

What did you set $NODE_VERSIONS and $NODE_VERSION_PREFIX to exactly?

**Comment by brandonpittman** [comment]
> We need someone that knows direnv well to explain what direnv expects inside `~/.local/share/nvm/v14.17.2`.

This. Their docs aren't very clear.

```
set -x NODE_VERSIONS /Users/blp/.local/share/nvm
set -x NODE_VERSION_PREFIX v
```

**Comment by jorgebucaran** [comment]
That definitely looks correct. Try setting $NODE_VERSION_PREFIX to `""` as well just in case.

If that doesn't work then I'm out of ideas for now.

**Comment by brandonpittman** [comment]
Tried that too, didn't work.

**Comment by thernstig** [comment]
@brandonpittman I use direnv together with fish and nvm.fish, and this is what I have in my `config.fish`:

```fish
if type -qf direnv
    # Load a Node.js version from a .node-version or .nvmrc file
    # from this path when using 'use node'
    set -gx NODE_VERSIONS ~/.local/share/nvm
    set -gx NODE_VERSION_PREFIX 'v'

    # Always keep at the end of this file
    direnv hook fish | source
end
```

**Comment by brandonpittman** [comment]
> ```fish
> if type -qf direnv
>     # Load a Node.js version from a .node-version or .nvmrc file
>     # from this path when using 'use node'
>     set -gx NODE_VERSIONS ~/.local/share/nvm
>     set -gx NODE_VERSION_PREFIX 'v'
> 
>     # Always keep at the end of this file
>     direnv hook fish | source
> end
> ```

Same error. Maybe it's me.

**Comment by thernstig** [comment]
> Same error. Maybe it's me.

I think it is 😆

**Comment by brandonpittman** [comment]
Son of a…I tried setting the prefix to `''` again—don't know why—and it worked.
