### ISSUE TITLE
Do not change fish_user_paths

### ISSUE THREAD

**Issue by thernstig** [jorgebucaran/nvm.fish#93]
Adding a path in the home directory to the universal var fish_user_paths is not ideal. For example, for my install of fish-nvm it becomes `SETUVAR 
 fish_user_paths:/home/myusername/\x2econfig/nvm/13\x2e0\x2e0/bin`

This is problematic due to the reason that some of us version control our home directory and certain parts of it, such as ~/.config/fish/ in order to have a unified working experience over multiple hosts.

Unfortunately there is no way to alter `fish_variables` so that it contains e.g. ~ (so it becomes agnostic as to what ny username is). This is due to that fish expands the path before adding it to `fish_variables` to the full path.

There are other reasons why setting an explicit user name is not ideal, such as in the case if a user changes his username. This would also invalidated the universal var set by fish-nvm. In short, no paths should be added to universal vars if they are a path in the user directory.

As such, it would be better to add the path to conf.d/nvm.fish as in there one can do `set -gx PATH ~/some/path` and it will be agnostic to the user name. It would also let me use different nodejs versions in different shells opened in fish.

**Comment by thernstig** [comment]
I can see the reason for wanting to use a universal var. One might want to change the node version across all shells at the same time. At the same time, sometimes you might want different versions in e.g. different tabs.

I have not tested this yet, but maybe a middle-ground could be that the conf.d files for fish-nvm checks the user name at shell startup and if it is different then what is found in the `fish_user_paths` it alters the nvm path at startup. At least, this way it is possible to share the config between different hosts easily.

**Comment by jorgebucaran** [comment]
@thernstig What problem are you having? What's broken? What didn't work?

**Comment by thernstig** [comment]
@jorgebucaran I was hoping that was clear from my initial post, but obviously I failed to get the point across :) What specific parts did you not understand, as I made several points in there. Or do you want to try to re-phrase the entire question (which I would be happy to do if needed)?

**Comment by thernstig** [comment]
Does this comment from me and faho's reply explain it better? https://github.com/fish-shell/fish-shell/issues/527#issuecomment-520771928

**Comment by jorgebucaran** [comment]
I think I get it now.

> @thernstig As such, it would be better to add the path to conf.d/nvm.fish as in there one can do set -gx PATH ~/some/path and it will be agnostic to the user name.

Sure, if that works for you, send me a PR.

**Comment by thernstig** [comment]
@jorgebucaran I see two solutions, but it depends on what you prefer.

1. Do you want `nvm use <version>` to still change all current shells nvm version? Like it currenlty does when using `fish_user_paths` to point to the bin dir.
2. Or do you want `nvm use <version>` to change current shell only (global exported var)?)

For 1) I see a solution of having `conf.d/nvm.fish` add `~/.config/nvm/bin/` to `PATH` and in that directory have a symlink to the used version. `nvm use <version>` would then just update the symlink instead.

Do you see drawbacks of such a change?

**Comment by jorgebucaran** [comment]
> @thernstig Do you want nvm use <version> to still change all current shells nvm version? Like it currently does when using fish_user_paths to point to the bin dir.

That's what I'd expect to happen, so (1) is best for me based on how I use fish-nvm.

**Comment by indeyets** [comment]
> > @thernstig Do you want nvm use  to still change all current shells nvm version? Like it currently does when using fish_user_paths to point to the bin dir.
> 
> That's what I'd expect to happen, so (1) is best for me based on how I use fish-nvm.

would it be possible to make this configurable somehow?
I usually find myself in situations when I do work on different projects which have different version-requirements and the whole point of NVM for me is to have project-specific nodejs versions

**Comment by andreiborisov** [comment]
@thernstig are you going to be satisfied with my solution https://github.com/jorgebucaran/fish-nvm/issues/101?

An option to use a global path variable instead of universal `fish_user_paths`. Do you want to affect all fish sessions while not using `fish_user_paths`? Is it important for you?

**Comment by thernstig** [comment]
@schrodincat I think it sounds good to support that `nvm use X` does not modify all session if hidden behind config. I believe it is orthogonal to my suggestion here in a sense As you can see in the pull request I sent in for this https://github.com/jorgebucaran/fish-nvm/pull/94 I changed it to not use `fish_user_paths` at all.

My problem is moreso that I believe `fish_user_paths` is bad. Reason is that it saves to `fish_variables`, and inside `fish_variables` a user might have a lot of setup they want to sync between hosts (like in my case). So I wanted to get rid of the dependency on that.

At the same time, I do think that `nvm use X` is nice to have to change the node version used for all open shells.

What you are trying to solve can already be solved by https://direnv.net/, which is what I do myself. It is also possibly a better solution as it solves many more things that just the node version. I do not even have to type any `nvm use X` when moving between projects, the correct version is autoloaded on entry in the directories. Would that not solve your problem?

**Comment by andreiborisov** [comment]
@thernstig thanks for the hint about `direnv`, it seems it will be quite easy to befriend it with this package🙌

**Comment by thernstig** [comment]
Here is a quick guide how to get it going:

Install node version 12.13.0 with nvm.
Install direnv.

Put this somewhere in your `config.fish` file.
```fish
# Node specific (for direnv to load)
set -gx NODE_VERSIONS ~/.config/nvm
set -gx NODE_VERSION_PREFIX ''

# Always keep at the end of this file
direnv hook fish | source
```

Put a `.nvmrc` file in your project dir with this content (as an example):
```sh
12.13.0
```

Put a `.envrc` file in your project dir with this content:
```sh
use node
layout node
watch_file .nvmrc
```

Now if you have another project with node, just repeat the .nvmrc and .envrc steps for that project, if you use node there. With another version if you will. It will automatically load the node env when you move between the project directories.

**Comment by thernstig** [comment]
I can add the same setup can be done for any language. I do it for e.g. Python, Go etc. etc. When I move between project directories I never have to think about loading the correct versions, it just happens.

**Comment by yegorius** [comment]
This has already been discussed in #39. Please see my last [comment](https://github.com/jorgebucaran/fish-nvm/issues/39#issuecomment-522186374) there. I hope @jorgebucaran will include proposed changes into official version, as this feature has been requested multiple times.
