### ISSUE TITLE
MSYS2 (Windows) support

### ISSUE THREAD

**Issue by Skehmatics** [jorgebucaran/nvm.fish#95]
Would love to see support for installations on Windows via [MSYS2](https://www.msys2.org/)

Current behavior:
```
$ nvm use lts
nvm: OS not implemented -- request it on https://git.io/fish-nvm
$ uname -smo
MSYS_NT-10.0-18362 x86_64 Msys
```

**Comment by jorgebucaran** [comment]
@Skehmatics Haha, you did the right thing. How can I get started working on this?

**Comment by Skehmatics** [comment]
To get the binaries, setting OS to win when detecting `uname -s` starting with `MSYS_NT`, as well as handling that the archive type will be .zip or .7z (modern tar can still extract these) rather than the hardcoded .tar.gz will be enough (see PR #96 )

I'm not sure how adding the binaries to the path works, however. We'll have node.exe (which will be aliased to just `node` by msys) and npm (no .exe for this one, apparently)

**Comment by Skehmatics** [comment]
Oh, duh, the other archives have the binaries in /bin, while the windows ones are just scattered about.

**Comment by jorgebucaran** [comment]
I just added Windows support in [2.0.1](https://github.com/jorgebucaran/nvm.fish/releases/tag/2.0.1). 👋

**Comment by RayBenefield** [comment]
Hey @jorgebucaran 

So just spent quite a bit of time debugging some stuff.

First is the `switch` check for the `$os` won't catch the proper case as you pipe it through `string lower` and the case check is in caps.

Second it doesn't seem like gzip is a big fan of `.zip` files if they have more than one file in them. See: https://superuser.com/questions/1237854/gzip-stdin-has-more-than-one-entry-rest-ignored-and-gzip-tmp-gz-has-more-t

On top of that the structure of the zip file isn't the same as other OSs... you'll get `npm` is actually in `node_modules/npm` not at the root of the directory like `node` so when you `nvm use` it tries to find the `package.json` at `$v/bin/npm/package.json` when it is actually at `$v/bin/node_modules/npm/package.json`.

It's all a mess... I have to dip for now. But wanted to at least put this all down before heading out.

**Comment by jorgebucaran** [comment]
@RayBenefield What are you trying to say?

**Comment by jorgebucaran** [comment]
@RayBenefield I already added Windows support. Are you saying it didn't work for you?

**Comment by jorgebucaran** [comment]
@RayBenefield I added Windows support a few weeks ago. Are you saying it isn't working for you?
