### ISSUE TITLE
Consider not overwriting .nvmrc when using it

### ISSUE THREAD

**Issue by briancavalier** [jorgebucaran/nvm.fish#97]
Thanks for fisher and this great little add-on.  I recently switched to it, and I love how simple and quick it is.

One thing I ran into recently, is that when I'm in a dir that has a .nvmrc file and I do `nvm` to switch to the .nvmrc node version, the .nvmrc gets overwritten with the same value but with a newline added if there wasn't one already.  While that doesn't cause a _problem_ per se, it does create a small annoyance in a GitHub repo with a .nvmrc that doesn't already have a newline.

My expectation was that this particular mode would be a read-only operation on .nvmrc, so I was surprised to see unstaged changes in a repo, e.g.:

```
❯ git status -sb
## master...origin/master

~/dev/jobdetails master
❯ cat .nvmrc
lts/*
~/dev/jobdetails master
❯ node --version
v8.17.0

~/dev/jobdetails master
❯ nvm

~/dev/jobdetails master*
❯ node --version
v12.14.0

~/dev/jobdetails master*
❯ git diff
diff --git a/.nvmrc b/.nvmrc
index 1a2f5bd..b009dfb 100644
--- a/.nvmrc
+++ b/.nvmrc
@@ -1 +1 @@
-lts/*
\ No newline at end of file
+lts/*
```

It's probably good for .nvmrc to have a newline, but it's not a requirement, and I don't always have control over all the repos I interact with that have a .nvmrc.

Would you be open to not overwriting .nvmrc in the case where `nvm` reads the .nvmrc version?

**Comment by jorgebucaran** [comment]
> @briancavalier Would you be open to not overwriting .nvmrc in the case where nvm reads the .nvmrc version?

Yes, I think this makes sense. 

Maybe all we need to do is not write to the `.nvmrc` file for `nvm` without arguments ([here](https://github.com/jorgebucaran/fish-nvm/blob/23648d9a82d4e46d60b6db60fcd6ecd4ca6a9987/functions/nvm.fish#L20)) and only for `nvm use xxx` ([here](https://github.com/jorgebucaran/fish-nvm/blob/23648d9a82d4e46d60b6db60fcd6ecd4ca6a9987/functions/nvm.fish#L17)). 

Do you think you can work on a PR?

**Comment by ljharb** [comment]
Probably you’d only want to write anything if the version is different - ie, still not add the newline even if i explicitly use the same version that’s in the nvmrc.

**Comment by jorgebucaran** [comment]
Meaning that if the `.nvmrc` has `lts` and the user executes `nvm use lts`, there's no need to write to the file either. Makes sense!

**Comment by briancavalier** [comment]
That sounds good to me as well, @ljharb.

> Do you think you can work on a PR?

I sure can.  It may take a bit with the holidays, but I'll get to it 😄
