### ISSUE TITLE
`nvm use` (with no arguments) as alias for `nvm`?

### ISSUE THREAD

**Issue by olets** [jorgebucaran/nvm.fish#99]
In switching over from (non-fish) nvm, I was tripped up by the "use the .nvmrc-specified version" command being `nvm` rather than `nvm use`. Would you be open to supporting argument-less `nvm use` to not diverge from nvm? What about having argument-less `nvm` output usage notes, like in nvm?

**Comment by jorgebucaran** [comment]
No, I prefer the way it works now, but thanks for the suggestion.
